spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/estate-base-test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
  jpa:
    show-sql: true
