spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

app:
  reminders:
    enabled: ${REMINDERS_ENABLED:false}
