spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
