CREATE TABLE ai_request_logs (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100),
    operation VARCHAR(100) NOT NULL,
    system_prompt VARCHAR(4000),
    user_prompt VARCHAR(8000) NOT NULL,
    metadata_json VARCHAR(8000),
    response_content VARCHAR(8000),
    status VARCHAR(30) NOT NULL,
    finish_reason VARCHAR(100),
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms BIGINT,
    error_message VARCHAR(4000),
    reference_type VARCHAR(100),
    reference_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_request_logs PRIMARY KEY (id),
    CONSTRAINT ck_ai_request_logs_status CHECK (
        status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'TIMEOUT')
    ),
    CONSTRAINT ck_ai_request_logs_tokens CHECK (
        (prompt_tokens IS NULL OR prompt_tokens >= 0)
        AND (completion_tokens IS NULL OR completion_tokens >= 0)
        AND (total_tokens IS NULL OR total_tokens >= 0)
    ),
    CONSTRAINT ck_ai_request_logs_latency CHECK (
        latency_ms IS NULL OR latency_ms >= 0
    )
);

CREATE INDEX idx_ai_request_logs_operation ON ai_request_logs (operation);
CREATE INDEX idx_ai_request_logs_reference ON ai_request_logs (reference_type, reference_id);
CREATE INDEX idx_ai_request_logs_created_at ON ai_request_logs (created_at);
