CREATE TABLE ai_recommendations (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    generated_by BIGINT NOT NULL,
    match_score INTEGER NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    suggested_action VARCHAR(1000) NOT NULL,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    ai_status VARCHAR(30) NOT NULL,
    provider VARCHAR(50),
    model VARCHAR(100),
    error_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_recommendations PRIMARY KEY (id),
    CONSTRAINT fk_ai_recommendations_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_recommendations_listing
        FOREIGN KEY (listing_id) REFERENCES listings (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_recommendations_generated_by
        FOREIGN KEY (generated_by) REFERENCES users (id),
    CONSTRAINT ck_ai_recommendations_score CHECK (match_score >= 0 AND match_score <= 100),
    CONSTRAINT ck_ai_recommendations_status CHECK (
        ai_status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'TIMEOUT')
    )
);

CREATE INDEX idx_ai_recommendations_customer_created
    ON ai_recommendations (customer_id, created_at);
CREATE INDEX idx_ai_recommendations_listing
    ON ai_recommendations (listing_id);
CREATE INDEX idx_ai_recommendations_generated_by
    ON ai_recommendations (generated_by, created_at);
