CREATE TABLE ai_lead_scores (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lead_id BIGINT NOT NULL,
    generated_by BIGINT NOT NULL,
    score INTEGER NOT NULL,
    priority VARCHAR(20) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    suggested_follow_up VARCHAR(1000) NOT NULL,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    ai_status VARCHAR(30) NOT NULL,
    provider VARCHAR(50),
    model VARCHAR(100),
    error_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_lead_scores PRIMARY KEY (id),
    CONSTRAINT fk_ai_lead_scores_lead
        FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_lead_scores_generated_by
        FOREIGN KEY (generated_by) REFERENCES users (id),
    CONSTRAINT ck_ai_lead_scores_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT ck_ai_lead_scores_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_ai_lead_scores_status CHECK (
        ai_status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'TIMEOUT')
    )
);

CREATE INDEX idx_ai_lead_scores_lead_created
    ON ai_lead_scores (lead_id, created_at);
CREATE INDEX idx_ai_lead_scores_generated_by
    ON ai_lead_scores (generated_by, created_at);
