CREATE TABLE ai_conversations (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    last_message_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_conversations PRIMARY KEY (id),
    CONSTRAINT fk_ai_conversations_created_by
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_ai_conversations_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX idx_ai_conversations_created_by
    ON ai_conversations (created_by, created_at);

CREATE TABLE ai_messages (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    content VARCHAR(8000) NOT NULL,
    ai_status VARCHAR(30),
    provider VARCHAR(50),
    model VARCHAR(100),
    error_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_messages PRIMARY KEY (id),
    CONSTRAINT fk_ai_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_messages_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    CONSTRAINT ck_ai_messages_status CHECK (
        ai_status IS NULL OR ai_status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'TIMEOUT')
    )
);

CREATE INDEX idx_ai_messages_conversation_created
    ON ai_messages (conversation_id, created_at);
