CREATE TABLE ai_image_analyses (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_image_id BIGINT NOT NULL,
    generated_by BIGINT NOT NULL,
    result_json VARCHAR(8000) NOT NULL,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    ai_status VARCHAR(30) NOT NULL,
    provider VARCHAR(50),
    model VARCHAR(100),
    error_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_image_analyses PRIMARY KEY (id),
    CONSTRAINT fk_ai_image_analyses_property_image
        FOREIGN KEY (property_image_id) REFERENCES property_images (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_image_analyses_generated_by
        FOREIGN KEY (generated_by) REFERENCES users (id),
    CONSTRAINT ck_ai_image_analyses_status CHECK (
        ai_status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'TIMEOUT')
    )
);

CREATE INDEX idx_ai_image_analyses_image_created
    ON ai_image_analyses (property_image_id, created_at);
